"""add agent analysis tables

Revision ID: 2799ebc745d0
Revises: 3ec690d1a625
Create Date: 2026-08-20 03:43:52.708336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2799ebc745d0'
down_revision: Union[str, Sequence[str], None] = '3ec690d1a625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('final_risk_level', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reviews_agent_version'), 'financial_reviews', ['agent_version'], unique=False)
    op.create_index(op.f('ix_financial_reviews_final_risk_level'), 'financial_reviews', ['final_risk_level'], unique=False)
    op.create_index(op.f('ix_financial_reviews_transaction_id'), 'financial_reviews', ['transaction_id'], unique=False)
    op.create_table('invoice_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('match_status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('mismatches', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_verifications_agent_version'), 'invoice_verifications', ['agent_version'], unique=False)
    op.create_index(op.f('ix_invoice_verifications_match_status'), 'invoice_verifications', ['match_status'], unique=False)
    op.create_index(op.f('ix_invoice_verifications_transaction_id'), 'invoice_verifications', ['transaction_id'], unique=False)
    op.create_table('transaction_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_analyses_agent_version'), 'transaction_analyses', ['agent_version'], unique=False)
    op.create_index(op.f('ix_transaction_analyses_risk_level'), 'transaction_analyses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_transaction_analyses_transaction_id'), 'transaction_analyses', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_analyses_transaction_id'), table_name='transaction_analyses')
    op.drop_index(op.f('ix_transaction_analyses_risk_level'), table_name='transaction_analyses')
    op.drop_index(op.f('ix_transaction_analyses_agent_version'), table_name='transaction_analyses')
    op.drop_table('transaction_analyses')
    op.drop_index(op.f('ix_invoice_verifications_transaction_id'), table_name='invoice_verifications')
    op.drop_index(op.f('ix_invoice_verifications_match_status'), table_name='invoice_verifications')
    op.drop_index(op.f('ix_invoice_verifications_agent_version'), table_name='invoice_verifications')
    op.drop_table('invoice_verifications')
    op.drop_index(op.f('ix_financial_reviews_transaction_id'), table_name='financial_reviews')
    op.drop_index(op.f('ix_financial_reviews_final_risk_level'), table_name='financial_reviews')
    op.drop_index(op.f('ix_financial_reviews_agent_version'), table_name='financial_reviews')
    op.drop_table('financial_reviews')
    # ### end Alembic commands ###
